// doctorProfileDummyData.js
import doc1 from "../assets/images/d1.jpg";
import doc2 from "../assets/images/d2.jpg";
import doc3 from "../assets/images/d3.jpg";
import doc4 from "../assets/images/d4.jpg";
import doc5 from "../assets/images/d5.jpg";
import doc6 from "../assets/images/d6.jpg";
import doc7 from "../assets/images/d7.jpg";
import doc8 from "../assets/images/d8.jpg";
import doc9 from "../assets/images/d9.jpg";
import doc10 from "../assets/images/d10.jpg";
import doc11 from "../assets/images/d11.jpg";
import doc12 from "../assets/images/d12.jpg";
import doc13 from "../assets/images/d13.jpg";
import doc14 from "../assets/images/d14.jpg";
import doc15  from "../assets/images/d15.jpg";
import doc16 from "../assets/images/d16.jpg";
import doc17 from "../assets/images/d17.jpg";
import doc18 from "../assets/images/d18.jpg";
import doc19 from "../assets/images/d19.jpg";
import doc20 from "../assets/images/d20.jpg";
import doc21 from "../assets/images/d21.jpg";


export const DOCTORS = [
  {
    id: 1,
    name: "Dr. Deepika Doshi",
    degree: "MBBS, MD",
    specialty: "Physician",
    experience: 12,
    rating: "4.8",
    reviews: 146,
    fee: 700,
    image: doc1,
    clinicName: "Dr. Deepika Doshi Clinic",
    clinicAddress: "Dhaval Apartment, Factory Lane, Borivali West, Mumbai - 400092",
    location: "Borivali West",
    city: "Mumbai",
    phone: "9324263464",
    landmark: "N/A",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4501",
    availability: "Mon-Sun: 12 AM - 12 PM",
    symptoms: ["Fever", "Cold", "General Consultation"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: true
  },
  {
    id: 2,
    name: "Dr. Kunal Arora",
    degree: "MBBS, MS",
    specialty: "Neurologist",
    experience: 10,
    rating: "4.7",
    reviews: 132,
    fee: 900,
    image: doc2,
    clinicName: "Apex Superspeciality Hospital",
    clinicAddress: "Apex Superspeciality Hospital, Borivali West, Mumbai - 400092",
    location: "Borivali West",
    city: "Mumbai",
    phone: "9004093090",
    landmark: "Beside Punjab & Sind Bank",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4502",
    availability: "Not Available",
    symptoms: ["Headache", "Migraine", "Neuro Consultation"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: false
  },
  {
    id: 3,
    name: "Dr. Amit Shah Neurology Clinic",
    degree: "MBBS, DM Neurology",
    specialty: "Neurologist",
    experience: 15,
    rating: "4.9",
    reviews: 188,
    fee: 1000,
    image: doc3,
    clinicName: "Dr. Amit Shah Neurology Clinic",
    clinicAddress: "Vasai West, Mumbai - 400092",
    location: "Vasai West",
    city: "Mumbai",
    phone: "9819561456",
    landmark: "N/A",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4503",
    availability: "Mon-Sat: 9:00 AM - 12:00 PM",
    symptoms: ["Headache", "Seizures", "Parkinson's"],
    about: "Experienced neurology clinic providing patient-centric and evidence-based treatment.",
    availableToday: true
  },
  {
    id: 4,
    name: "Dr. Indu Bubna",
    degree: "MBBS, MD",
    specialty: "Physician",
    experience: 18,
    rating: "4.8",
    reviews: 165,
    fee: 800,
    image: doc4,
    clinicName: "SBS Hospital",
    clinicAddress: "SBS Hospital, Andheri West, Mumbai - 400053",
    location: "Andheri West",
    city: "Mumbai",
    phone: "9920071302",
    landmark: "SBS Hospital",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4504",
    availability: "Mon-Sat: 9:00 AM - 9:00 PM, Sunday: Holiday",
    symptoms: ["Fever", "Diabetes", "BP"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: true
  },
  {
    id: 5,
    name: "Dr. Parthiv Shah",
    degree: "MBBS, MD",
    specialty: "Physician",
    experience: 14,
    rating: "4.7",
    reviews: 154,
    fee: 750,
    image: doc5,
    clinicName: "Dr. Parthiv Shah Clinic",
    clinicAddress: "Dahisar East, Mumbai - 400068",
    location: "Dahisar East",
    city: "Mumbai",
    phone: "9029772904",
    landmark: "N/A",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4505",
    availability: "Sunday: 9 AM - 8 PM; Mon-Fri: 9 AM - 10 PM; Saturday: 9 AM - 10 PM",
    symptoms: ["General Consultation", "BP", "Diabetes"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: true
  },
  {
    id: 6,
    name: "NeuroPlus Epilepsy & Parkinson's Clinic",
    degree: "MBBS, DM Neurology",
    specialty: "Neurologist",
    experience: 16,
    rating: "4.8",
    reviews: 176,
    fee: 1200,
    image:doc6,
    clinicName: "NeuroPlus Epilepsy & Parkinson's Clinic",
    clinicAddress: "Mumbai - 400056",
    location: "Mumbai",
    city: "Mumbai",
    phone: "02248971800",
    landmark: "N/A",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4506",
    availability: "Not Available",
    symptoms: ["Epilepsy", "Parkinson's", "Seizures"],
    about: "Specialized neurology clinic focused on epilepsy, Parkinson's and related neurological care.",
    availableToday: false
  },
  {
    id: 7,
    name: "Arogyam Eye Clinic",
    degree: "MBBS, MS Ophthalmology",
    specialty: "Ophthalmologist",
    experience: 11,
    rating: "4.6",
    reviews: 121,
    fee: 600,
    image: doc7,
    clinicName: "Arogyam Eye Clinic",
    clinicAddress: "Jangal Mangal Road, Mumbai - 400078",
    location: "Jangal Mangal Road",
    city: "Mumbai",
    phone: "9136691777",
    landmark: "Opp PMC Bank",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4507",
    availability: "Not Available",
    symptoms: ["Eye Checkup", "Blurred Vision", "Cataract"],
    about: "Eye care clinic providing consultation and treatment for common and advanced eye conditions.",
    availableToday: false
  },
  {
    id: 8,
    name: "Dr. Turabi Mazhar Abbas",
    degree: "MBBS, MD",
    specialty: "Physician",
    experience: 9,
    rating: "4.5",
    reviews: 118,
    fee: 650,
    image: doc8,
    clinicName: "Dr. Turabi Mazhar Abbas Clinic",
    clinicAddress: "Kurla West, Mumbai - 400070",
    location: "Kurla West",
    city: "Mumbai",
    phone: "8425884110",
    landmark: "N/A",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4508",
    availability: "Sunday: AM to PM; Tue/Thu/Sat: 3:00 AM - 5:00 PM; Mon/Wed/Fri: AM to PM",
    symptoms: ["General Consultation", "Fever", "Cold"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: true
  },
  {
    id: 9,
    name: "Dr. Gurneet Sawhney",
    degree: "MBBS, MS",
    specialty: "Neurologist",
    experience: 13,
    rating: "4.8",
    reviews: 162,
    fee: 1100,
    image:doc9,
    clinicName: "Dr. Gurneet Sawhney Clinic",
    clinicAddress: "Mulund West, Mumbai - 400082",
    location: "Mulund West",
    city: "Mumbai",
    phone: "8104310753",
    landmark: "N/A",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4509",
    availability: "Not Available",
    symptoms: ["Headache", "Migraine", "Neuro Care"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: false
  },
  {
    id: 10,
    name: "Dr. Salil Patkar",
    degree: "MBBS, MD",
    specialty: "Physician",
    experience: 12,
    rating: "4.7",
    reviews: 149,
    fee: 800,
    image: doc10,
    clinicName: "Dr. Salil Patkar Clinic",
    clinicAddress: "Vashi, Mumbai - 400703",
    location: "Vashi",
    city: "Mumbai",
    phone: "8451069854",
    landmark: "Above Golden Punjab Restaurant",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4510",
    availability: "Sun: 9 AM - 10 PM; Mon-Fri: 9 AM - 10 PM; Sat: 9 AM - 10 PM",
    symptoms: ["Fever", "BP", "Diabetes"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: true
  },
  {
    id: 11,
    name: "Dr. Samir Mehta",
    degree: "MBBS, MD",
    specialty: "Cardiologist",
    experience: 17,
    rating: "4.8",
    reviews: 171,
    fee: 1000,
    image:doc11,
    clinicName: "Dr. Samir Mehta Clinic",
    clinicAddress: "Santacruz West, Mumbai",
    location: "Santacruz West",
    city: "Mumbai",
    phone: "9820363914",
    landmark: "N/A",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4511",
    availability: "9:00 AM - 9:00 PM",
    symptoms: ["Chest Pain", "BP", "Heart Checkup"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: true
  },
  {
    id: 12,
    name: "Dr. A. B. Modi",
    degree: "MBBS, MD",
    specialty: "Physician",
    experience: 20,
    rating: "4.7",
    reviews: 160,
    fee: 750,
    image: doc12,
    clinicName: "Dr. A. B. Modi Clinic",
    clinicAddress: "Mumbai - 400004",
    location: "Mumbai",
    city: "Mumbai",
    phone: "02223684281",
    landmark: "Above SBI",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4512",
    availability: "Not Available",
    symptoms: ["General Consultation", "Fever", "BP"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: false
  },
  {
    id: 13,
    name: "Dr. Alpana S Khare",
    degree: "MBBS, MD",
    specialty: "Dermatologist",
    experience: 11,
    rating: "4.6",
    reviews: 137,
    fee: 850,
    image: doc13,
    clinicName: "Dr. Alpana S Khare Clinic",
    clinicAddress: "CBD Belapur, Navi Mumbai",
    location: "CBD Belapur",
    city: "Navi Mumbai",
    phone: "9653110367",
    landmark: "N/A",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4513",
    availability: "Not Available",
    symptoms: ["Skin Rash", "Acne", "Hair Fall"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: false
  },
  {
    id: 14,
    name: "Dr. Sujit K Prasad",
    degree: "MBBS, MD",
    specialty: "Physician",
    experience: 13,
    rating: "4.7",
    reviews: 144,
    fee: 800,
    image:doc14,
    clinicName: "Dr. Sujit K Prasad Clinic",
    clinicAddress: "Nerul, Mumbai",
    location: "Nerul",
    city: "Mumbai",
    phone: "9820146225",
    landmark: "N/A",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4514",
    availability: "Not Available",
    symptoms: ["Fever", "General Consultation", "Diabetes"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: false
  },
  {
    id: 15,
    name: "Dr. Niketa Sonavane",
    degree: "MBBS, MD",
    specialty: "Gynecologist",
    experience: 10,
    rating: "4.8",
    reviews: 151,
    fee: 900,
    image: doc15,
    clinicName: "Dr. Niketa Sonavane Clinic",
    clinicAddress: "Andheri West, Mumbai",
    location: "Andheri West",
    city: "Mumbai",
    phone: "02240022442 / 9930993600",
    landmark: "1st Cross Lane",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4515",
    availability: "Mon-Sat: 11 AM - 7 PM, Sunday Holiday",
    symptoms: ["Pregnancy Care", "Women's Health", "PCOS"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: true
  },
  {
    id: 16,
    name: "Dr. Atul Choksi",
    degree: "MBBS, MD",
    specialty: "Physician",
    experience: 19,
    rating: "4.7",
    reviews: 166,
    fee: 850,
    image: doc16,
    clinicName: "Dr. Atul Choksi Clinic",
    clinicAddress: "Mumbai - 400064",
    location: "Mumbai",
    city: "Mumbai",
    phone: "9821360959",
    landmark: "Opp Life Line Hospital",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4516",
    availability: "Not Available",
    symptoms: ["General Consultation", "BP", "Diabetes"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: false
  },
  {
    id: 17,
    name: "Dr. Aniruddha Bhuiyan",
    degree: "MBBS, MD",
    specialty: "Physician",
    experience: 12,
    rating: "4.6",
    reviews: 140,
    fee: 750,
    image:doc17,
    clinicName: "Dr. Aniruddha Bhuiyan Clinic",
    clinicAddress: "Andheri East, Mumbai",
    location: "Andheri East",
    city: "Mumbai",
    phone: "9819588248",
    landmark: "N/A",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4517",
    availability: "Not Available",
    symptoms: ["Fever", "Cold", "General Consultation"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: false
  },
  {
    id: 18,
    name: "Health Total",
    degree: "Nutrition & Wellness Care",
    specialty: "Physician",
    experience: 10,
    rating: "4.5",
    reviews: 128,
    fee: 700,
    image:doc18,
    clinicName: "Health Total",
    clinicAddress: "Andheri East, Mumbai",
    location: "Andheri East",
    city: "Mumbai",
    phone: "02261793629 / 7045929943",
    landmark: "N/A",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4518",
    availability: "Sun: 10 AM - 4 PM, Mon-Fri: 10 AM - 7 PM, Sat: 10 AM - 6 PM",
    symptoms: ["Weight Management", "Diabetes", "Lifestyle Care"],
    about: "Healthcare and wellness center providing patient-centric consultation and care.",
    availableToday: true
  },
  {
    id: 19,
    name: "Dr. Surbhi Trivedi",
    degree: "MBBS, MD",
    specialty: "Physician",
    experience: 9,
    rating: "4.6",
    reviews: 133,
    fee: 750,
    image: doc19,
    clinicName: "Dr. Surbhi Trivedi Clinic",
    clinicAddress: "Vile Parle West, Mumbai",
    location: "Vile Parle West",
    city: "Mumbai",
    phone: "9820399867",
    landmark: "Opp CNMS School",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4519",
    availability: "Mon-Sat: 5 PM - 7 PM, Sunday Holiday",
    symptoms: ["General Consultation", "Fever", "BP"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: true
  },
  {
    id: 20,
    name: "Dr. Amit Gandhi",
    degree: "MBBS, MD",
    specialty: "Cardiologist",
    experience: 15,
    rating: "4.8",
    reviews: 172,
    fee: 1000,
    image: doc20,
    clinicName: "Dr. Amit Gandhi Clinic",
    clinicAddress: "Parel, Mumbai",
    location: "Parel",
    city: "Mumbai",
    phone: "8104225500",
    landmark: "N/A",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4520",
    availability: "Not Available",
    symptoms: ["Chest Pain", "Heart Checkup", "BP"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: false
  },
  {
    id: 21,
    name: "Dr. Ravindra Dargainya",
    degree: "MBBS, MD",
    specialty: "Physician",
    experience: 14,
    rating: "4.6",
    reviews: 139,
    fee: 800,
    image: doc21,
    clinicName: "Dr. Ravindra Dargainya Clinic",
    clinicAddress: "Bandra West, Mumbai",
    location: "Bandra West",
    city: "Mumbai",
    phone: "N/A",
    landmark: "Above Tavaa Restaurant",
    languages: ["English", "Hindi", "Marathi"],
    registrationNo: "MMC/2012/4521",
    availability: "9:30 AM - 6:30 AM",
    symptoms: ["General Consultation", "Fever", "Diabetes"],
    about: "Experienced doctor providing patient-centric, ethical and evidence-based treatment.",
    availableToday: true
  }
];
export default DOCTORS;